* Avoiding Jargon

Consider these sentences. How would we edit them? 

1. The financial analyst claimed that because of volatile market conditions, she could not make an estimate of the company’s future profits.
2. Investigators were involved in studying the effect of classical music on unborn babies.
3. There is another module that tells the story of Charles Darwin and introduces the theory of evolution.
4. It is imperative that all night managers follow strict procedures when locking the safe.

Edit the following sentences to avoid the use of jargon, pretentious language, and doublespeak. 

1. In my youth, my family was under the constraints of difficult financial circumstances.
2. In order that I may increase my expertise in the area of delivery of services to clients, I feel that participation in this conference will be beneficial.
3. The prophetic meteorologist cautioned the general populace regarding the possible deleterious effects of the impending tempest.
4. Governmentally sanctioned investigations into the continued value of after-school programs indicate a perceived need in the public realm at large.
5. Passengers should endeavor to finalize the customs declaration form prior to exiting the aircraft.
6. We learned that the mayor had been engaging in a creative transfer of city employees’ pension funds.
7. After a cursory examination of brand-new research findings on textiles, Patricia and the members of her team made the decision to engage in a series of visits to fashion manufacturers in the local vicinity.
8. The nurse announced that there had been a negative patient care outcome due to a therapeutic misadventure on the part of the surgeon.
9. A generally leisurely pace at the onset of tai chi exercises can yield a variety of beneficial points within a short period of time.
10. The bottom line is that the company is experiencing a negative cash flow.

Edit the following email to avoid the use of jargon: 

Dear Ms. Jackson:

We members of the Nakamura Reyes team value our external partnering arrangements with Creative Software, and I look forward to seeing you next week at the trade show in Fresno. Per Mr. Reyes, please let me know when you’ll have some downtime there so that he and I can conduct a strategizing session with you concerning our production schedule. It’s crucial that we all be on the same page re our 2009–2010 product release dates.

Before we have some face time, however, I have some findings to share. Our customer-centric approach to the new products will necessitate that user testing periods trend upward. The enclosed data should help you effectuate any adjustments to your timeline; let me know ASAP if you require any additional information to facilitate the above. Before we convene in Fresno, Mr. Reyes and I will agendize any further talking points. Thanks for your help.

Sincerely,

Sylvia Nakamura
