* Exercise: Tighten Wordy Sentences

In-class exercise: edit these sentences, removing words and phrases to tighten them.

1. Martin Luther King Jr. was a man who set a high standard for future leaders to meet.
2. Alice has been deeply in love with cooking since she was little and could first peek over the edge of a big kitchen tabletop.
3. In my opinion, Bloom’s race for the governorship is a futile exercise.
4. It is pretty important in being a successful graphic designer to have technical knowledge and at the same time an eye for color and balance.
5. Your task will be the delivery of correspondence to all employees in the company. 
6. Seeing the barrels, the driver immediately slammed on his brakes.
7. A really well-stocked bookshelf should have classical literature on it as well as important modern works of the current day.
8. China’s enormously huge workforce has an effect on the global world of high-tech manufacturing of things.
9. A typical autocross course consists of at least two straightaways, and the rest of the course is made up of numerous slaloms and several sharp turns.
10. At breakfast time, Mehrdad always started his day with cantaloupe, lemon yogurt, and black coffee.
 
