* University Writing: P1 Paper Prompt
(adapted from an assignment by Aaron Ritzenberg)

Critical Inquiry 

Pick a single passage from Turing, "Computing Machinery and Intelligence," Freud, "The Uncanny," or Halberstam, "Automating Gender," that contains an intellectual *problem* you wish to explore. A problem can take the form of a tension, an ambiguity, a contradiction, or another similar issue. The passage can be as short as a single paragraph and should not be longer than a single page. Make a *claim* about how the writer's choices of language and form affect the argument. Your analysis should stay close to the text, using the methods and terminology we discuss in class. The paper should be 1200-1500 words long. 
 
Goals:

- Identify a *problem* that is worth addressing, using a passage that will reward *close reading*.

- Formulate a *claim* that makes a strong argument and is not obvious.

- Establish a *motive* for the essay in your *introduction*. Here you will answer the “So What?” question, suggesting why your essay is important and interesting to an intelligent reader. Draw out the implications of the argument in your *conclusion*.

- *Structure* the essay around your central claim, making sure that each paragraph is adding an essential piece to your argument.
 
- Use *evidence* persuasively, quoting from the text when necessary, summarizing or paraphrasing accurately and responsibly when appropriate. Do not provide evidence from other sources or make general assertions (e.g., claims about “human nature”).

** Drafts
*** Exploratory Draft, due Thursday, September 14th
Write a partial draft of three pages that includes at least two pages of polished prose. The unpolished sections of the partial draft can take the form of an outline or notes, though the general shape and argument of your paper should be apparent. Continue to think about the central *problem* that you are exploring. Is the problem resolved? Is the resolution (or absence of resolution) significant to the argument? Think about the *motive* of your *claim*. How does your claim and analysis help us to understand the text's ideas in a new way?

*** Formal Draft, due Wednesday, September 20th 
Make your formal draft as polished as possible. Think of it as a final draft. The better this draft is, the better your final draft will be. 

- Post your paper in the assignments section of CourseWorks before midnight. If you've never posted an assignment to CourseWorks before, allot an extra hour or so to figure it out. 
- Bring a printed copy of your paper to class on Thursday, September 21st to prepare for peer review. If this is your first time using the Columbia print system ("PawPrint"), allot some extra time to familiarize yourself with the system.

*** Final Draft, due Monday, October 2nd
Your final draft should be a *radical* rewrite of your essay, taking into account instructor and peer feedback, but not merely responding to it. In other words, instead of correcting the occasional misspelled word, or tightening a few wordy sentences, make substantial and well-considered improvements to the structure and syntax or your essay. Post your final paper to the assignments section on CourseWorks.
