* P4 Prompt 

Op-ed

Write an op-ed on a topic of your choosing that has currency and relevance for your intended audience. Make it your best piece of writing ever. Use all the relevant techniques you've learned from P1-P3. Make a specific *claim* about your topic, and make sure you have a clear *motive*. Tailor your op-ed to your target publication. Unless your publication has a house style (Chicago, APA, NYT, etc.), use MLA format, and unless your publication requires a specific word length, make your op-ed about 750 words. 

** Plan
Draft a concise plan for your op-ed. This should include: 
 - *Target publication*. Where you intend to submit your final draft. 
 - *Submission guidelines*. Your target publication's submission guidelines. Answer, if you can: 
   - What style and format do they require? MLA? Chicago?    
   - What is the word length they require? (If they do not explictly require a word length, find the average word length of a few of their op-eds.)
 - *Audience*. The audience of this publication. 
   - What is that audience like? 
   - How will you adjust your style and tone to appeal to this audience? 
 - *Motivations*. 
   - Why this? 
   - Why you? 
   - Why now?

Include a draft of an introductory paragraph in your plan. Revise it a few times before submitting. 

** Final Draft
Write an op-ed and prepare it for submission to your target publication. Include a 1-3 sentence bio.

Submit your draft to your target publication. After submitting it, post it to CourseWorks in PDF format. In the comments section of CourseWorks, note the word count, and the publication to which you submitted. Additionally, in about one paragraph, describe your writing and submission process. What was it like going public? 
